CREATE DATABASE IF NOT EXISTS Bookshop;

USE `Bookshop`;

CREATE USER IF NOT EXISTS 'Customer' IDENTIFIED BY '123';
CREATE USER IF NOT EXISTS 'Provider' IDENTIFIED BY '456';
CREATE USER IF NOT EXISTS 'Admin' IDENTIFIED BY '789';

GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'Provider';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'Customer';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'Admin';

